### PR TITLE
Adding Export Vendor Configuration page

### PR DESCRIPTION
**Pull request by lychiang**
## Description

Adding one side-bar -Export Vendor Configuration and add a page- expedition_export.md for showing how to export vendor's configurations.

## Motivation and Context

Instructions required for customers. 

## How Has This Been Tested?

New changes and tested in local machine

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [x ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [x ] I have added tests to cover my changes if appropriate.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Review by csestito — CHANGES_REQUESTED** [review]
Can you remove all of the venv/* files from this commit?

**Comment by lychiang** [comment]
How to do that ?

Lynn

*Lynn Chiang | **Developer Relations, Technical Solutions Architect*

Palo Alto Networks  |  3000 Tannery Way  |  Santa Clara, CA 95054  |  USA

www.paloaltonetworks.com


<https://www.paloaltonetworks.com/>
<https://www.linkedin.com/company/palo-alto-networks>
<https://www.facebook.com/PaloAltoNetworks/>
<https://twitter.com/PaloAltoNtwks>

The content of this message is the proprietary and confidential property of
Palo Alto Networks, and should be treated as such. If you are not the
intended recipient and have received this message in error, please delete
this message from your computer system and notify me immediately by e-mail.
Any unauthorized use or distribution of the content of this message is
prohibited.

**Comment by lychiang** [comment]
Have maded a changed to remove everything under venv/

**Review by csestito — APPROVED** [review]
Looks good now, thanks!

**Pull request merged**
